"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-12 02:50:38.760196
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("target_duration", sa.Float(), nullable=False),
        sa.Column("aspect_ratio", sa.String(length=20), nullable=False),
        sa.Column("resolution_profile", sa.String(length=30), nullable=False),
        sa.Column("fps", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("root_asset_directory", sa.Text(), nullable=False),
        sa.Column("default_providers", sa.JSON(), nullable=False),
        sa.Column("global_visual_style", sa.Text(), nullable=False),
        sa.Column("global_negative_prompt", sa.Text(), nullable=False),
        sa.Column("seed_policy", sa.JSON(), nullable=False),
        sa.Column("original_story", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("canonical_appearance", sa.Text(), nullable=False),
        sa.Column("personality_notes", sa.Text(), nullable=False),
        sa.Column("wardrobe_rules", sa.Text(), nullable=False),
        sa.Column("color_palette", sa.JSON(), nullable=False),
        sa.Column("reference_images", sa.JSON(), nullable=False),
        sa.Column("expression_references", sa.JSON(), nullable=False),
        sa.Column("pose_references", sa.JSON(), nullable=False),
        sa.Column("negative_identity_traits", sa.Text(), nullable=False),
        sa.Column("model_references", sa.JSON(), nullable=False),
        sa.Column("consent_provenance", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_project_id"), "characters", ["project_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=True),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("gpu_assignment", sa.String(length=20), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("current_stage", sa.String(length=120), nullable=False),
        sa.Column("error_info", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("log_path", sa.Text(), nullable=True),
        sa.Column("input_asset_ids", sa.JSON(), nullable=False),
        sa.Column("output_asset_ids", sa.JSON(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_project_id"), "jobs", ["project_id"], unique=False)
    op.create_index(op.f("ix_jobs_state"), "jobs", ["state"], unique=False)
    op.create_table(
        "renders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("render_profile", sa.String(length=40), nullable=False),
        sa.Column("included_scene_ids", sa.JSON(), nullable=False),
        sa.Column("included_shot_ids", sa.JSON(), nullable=False),
        sa.Column("output_path", sa.Text(), nullable=False),
        sa.Column("codec", sa.String(length=40), nullable=False),
        sa.Column("resolution", sa.String(length=30), nullable=False),
        sa.Column("frame_rate", sa.Float(), nullable=False),
        sa.Column("audio_configuration", sa.JSON(), nullable=False),
        sa.Column("subtitle_configuration", sa.JSON(), nullable=False),
        sa.Column("creation_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_renders_project_id"), "renders", ["project_id"], unique=False)
    op.create_table(
        "scenes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("time_of_day", sa.String(length=80), nullable=False),
        sa.Column("lighting", sa.Text(), nullable=False),
        sa.Column("characters", sa.JSON(), nullable=False),
        sa.Column("props", sa.JSON(), nullable=False),
        sa.Column("environment", sa.Text(), nullable=False),
        sa.Column("continuity_state", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenes_project_id"), "scenes", ["project_id"], unique=False)
    op.create_table(
        "shots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("shot_type", sa.String(length=80), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=False),
        sa.Column("dialogue", sa.Text(), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("speaker", sa.String(length=120), nullable=True),
        sa.Column("camera", sa.JSON(), nullable=False),
        sa.Column("character_positions", sa.JSON(), nullable=False),
        sa.Column("character_actions", sa.JSON(), nullable=False),
        sa.Column("planned_start_frame_id", sa.String(length=36), nullable=True),
        sa.Column("planned_end_frame_id", sa.String(length=36), nullable=True),
        sa.Column("actual_start_frame_id", sa.String(length=36), nullable=True),
        sa.Column("actual_end_frame_id", sa.String(length=36), nullable=True),
        sa.Column("continuity_source_frame_id", sa.String(length=36), nullable=True),
        sa.Column("continuity_target_frame_id", sa.String(length=36), nullable=True),
        sa.Column("continuity_source_shot_id", sa.String(length=36), nullable=True),
        sa.Column("transition_type", sa.String(length=40), nullable=False),
        sa.Column("overlap_frame_count", sa.Integer(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("generation_settings", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("approval_state", sa.String(length=30), nullable=False),
        sa.Column("selected_candidate_id", sa.String(length=36), nullable=True),
        sa.Column("rejected_candidate_ids", sa.JSON(), nullable=False),
        sa.Column("continuity_packet", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shots_scene_id"), "shots", ["scene_id"], unique=False)
    op.create_table(
        "voice_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("reference_audio", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("speaking_style", sa.String(length=100), nullable=False),
        sa.Column("speed", sa.Float(), nullable=False),
        sa.Column("pitch", sa.Float(), nullable=False),
        sa.Column("emotion_defaults", sa.JSON(), nullable=False),
        sa.Column("consent_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_voice_profiles_character_id"), "voice_profiles", ["character_id"], unique=False
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("frame_rate", sa.Float(), nullable=True),
        sa.Column("source_provider", sa.String(length=80), nullable=False),
        sa.Column("model_identifier", sa.String(length=120), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("generation_parameters", sa.JSON(), nullable=False),
        sa.Column("parent_asset_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_path"),
    )
    op.create_index(op.f("ix_assets_project_id"), "assets", ["project_id"], unique=False)
    op.create_index(op.f("ix_assets_shot_id"), "assets", ["shot_id"], unique=False)
    op.create_table(
        "candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("generation_seconds", sa.Float(), nullable=False),
        sa.Column("gpu", sa.String(length=20), nullable=False),
        sa.Column("input_asset_ids", sa.JSON(), nullable=False),
        sa.Column("output_asset_id", sa.String(length=36), nullable=True),
        sa.Column("first_frame_asset_id", sa.String(length=36), nullable=True),
        sa.Column("last_frame_asset_id", sa.String(length=36), nullable=True),
        sa.Column("qa_results", sa.JSON(), nullable=False),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column("disposition", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candidates_shot_id"), "candidates", ["shot_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candidates_shot_id"), table_name="candidates")
    op.drop_table("candidates")
    op.drop_index(op.f("ix_assets_shot_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_project_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_voice_profiles_character_id"), table_name="voice_profiles")
    op.drop_table("voice_profiles")
    op.drop_index(op.f("ix_shots_scene_id"), table_name="shots")
    op.drop_table("shots")
    op.drop_index(op.f("ix_scenes_project_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_renders_project_id"), table_name="renders")
    op.drop_table("renders")
    op.drop_index(op.f("ix_jobs_state"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_project_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_characters_project_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_table("projects")
    # ### end Alembic commands ###
